AWSTemplateFormatVersion: '2010-09-09'
Description: AWS Step Functions sample project for Universal Integration
Resources:
  StatesExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Service: states.amazonaws.com
            Action: 'sts:AssumeRole'
      Path: '/'
      Policies:
        - PolicyName: StatesExecutionPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'comprehend:DetectSentiment'
                Resource:
                  - '*'
      RoleName: UniversalSDKRoleNameforStepfunctions